parameters:
    efl.form.type.cart.class: Efl\BasketBundle\Form\Type\CartType

services:
    efl.form.cart:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - efl_cart_form                        # name of the form
            - efl_cart
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    efl.form.type.cart:
        class: %efl.form.type.cart.class%
        arguments:
            - @eflweb.basket_service
        tags:
            - { name: form.type, alias: efl_cart }
