parameters:
    eflweb.listener.discounts.class: Efl\BasketBundle\Listeners\Discounts

services:
    eflweb.listener.basket.applydiscounts:
        class: %eflweb.listener.discounts.class%
        arguments:
            - @efl.basket.discounts
            - @eflweb.basket_service
        tags:
            - { name: kernel.event_listener, event: eflweb.event.basket.preshow, method: applyDiscountsToBasket }
