parameters:
    # API services
    eflweb.basket_service.class: Efl\BasketBundle\eZ\Publish\Core\Repository\BasketService
    eflweb.persistence.legacy.basket.handler.class: Efl\BasketBundle\eZ\Publish\Core\Persistence\Legacy\Basket\Handler
    eflweb.persistence.legacy.basket.gateway.class: Efl\BasketBundle\eZ\Publish\Core\Persistence\Legacy\Basket\Gateway\Legacy
    ezprice.api.storage_engine.legacy.handler.ezprice.eflautomaticvathandler.class: Efl\BasketBundle\Core\Persistence\Legacy\Price\VatHandler\EflAutomaticVatHandler
    eflweb.cart_helper.class: Efl\BasketBundle\Helper\CartHelper
    eflweb.persistence.legacy.basket.related.class: Efl\BasketBundle\eZ\Publish\Core\Persistence\Legacy\Basket\Gateway\RelatedByOrders

services:
    eflweb.basket_service:
        class: %eflweb.basket_service.class%
        arguments:
            - @eflweb.persistence.legacy.basket.handler
            - @ezpublish.api.service.content
            - @event_dispatcher
            - @efl.basket.shipping

    eflweb.persistence.legacy.basket.handler:
        class: %eflweb.persistence.legacy.basket.handler.class%
        arguments:
            - @eflweb.persistence.legacy.basket.gateway.inner
            - @ezpublish.api.service.content

    eflweb.persistence.legacy.basket.gateway.inner:
        class: %eflweb.persistence.legacy.basket.gateway.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content_type
            - @eflweb.persistence.legacy.basket.related
            - @ezprice.api.service.contentvatservice
            - @ezpublish.api.repository
            - @doctrine.orm.entity_manager
            - @session
        calls:
            - [setConnection, [@ezpublish.api.storage_engine.legacy.dbhandler]]

    ezprice.api.storage_engine.legacy.handler.ezprice.eflautomaticvathandler:
        class: %ezprice.api.storage_engine.legacy.handler.ezprice.eflautomaticvathandler.class%
        arguments:
            - @eflweb.utils_helper
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.api.service.content
             # las palmas, santa cruz de tenerife, ceuta y melilla
            - [35, 38, 51, 52]

    ezprice.api.service.automaticvatservice:
        class: %ezprice.api.service.automaticvatservice.class%
        arguments:
            - @ezprice.api.storage_engine.legacy.handler.ezprice.eflautomaticvathandler

    eflweb.cart_helper:
        class: %eflweb.cart_helper.class%
        arguments: [@ezpublish.api.service.content_type]

    eflweb.persistence.legacy.basket.related:
        class: %eflweb.persistence.legacy.basket.related.class%
