sudo: required
dist: trusty
language: php

# run tests on php misc php versions
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 5.3

# test only master (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

# setup requirements for running unit tests
before_script:
  # Disable xdebug to speed things up as we don't currently generate coverage on travis
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Token below is reserved for testing against ezsystems repos (& forks), it has same rights as anonymous, but authenticates against github api.
  # For your own organization please create your own token without(!) any scope to avoid both you and us reaching api limitations on this token.  
  - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
  # Install packages using composer
  - travis_retry composer install --dev --prefer-dist --no-interaction --optimize-autoloader

# execute phpunit as the script command
script: php vendor/bin/phpunit --colors -c phpunit.xml

# disable mail notifications
notification:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30
