Efl\DiscountsBundle\Entity\Ezdiscountsubrule:
    type: entity
    table: ezdiscountsubrule
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        discountPercent:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: discount_percent
        discountruleId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: discountrule_id
        limitation:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
    lifecycleCallbacks: {  }
