siteaccess:
    groups:
        efl_frontend_group:
            - newhome
            - formacion
system:
    efl_frontend_group:
        location_view:
            full:
                producto:
                    template: "EflWebBundle:full:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
    global:
        field_templates:
            - {template: "EflWebBundle::content_fields.html.twig", priority: 10}