siteaccess:
    groups:
        efl_frontend_group:
            - newhome
            - formacion
system:
    efl_frontend_group:
        image_variations:
            ebook_regalo:
                reference: original
                filters:
                    - { name: geometry/scalewidthdownonly, params: [480] }
            portrait:
                reference: original
                filters:
                    - { name: geometry/scalewidthdownonly, params: [480] }
            foto_testimonio:
                reference: original
                filters:
                    - { name: geometry/scale, params: [162,162] }
        content_view:
            ebook_regalo:
                ebook:
                    template: "EflWebBundle:ebook_regalo:ebook_regalo.html.twig"
                    match:
                        Identifier\ContentType: [ebook]
        location_view:
            video:
                producto:
                    controller: "EflWebBundle:Product:full"
                    template: "EflWebBundle:video:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
            summary:
                producto:
                    controller: "EflWebBundle:Product:full"
                    template: "EflWebBundle:full:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
            preview:
                producto:
                    controller: "EflWebBundle:Product:full"
                    template: "EflWebBundle:full:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
            full:
                home:
                    template: "EflWebBundle:full:home.html.twig"
                    match:
                        Id\Location: 2
                producto:
                    controller: "EflWebBundle:Product:full"
                    template: "EflWebBundle:full:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
                carpeta_section_nosotros:
                    controller: "EflWebBundle:Nosotros:page"
                    template: "EflWebBundle:full:carpeta_nosotros.html.twig"
                    match:
                        Identifier\ContentType: [folder]
                        Id\Section: 10
                faqs:
                    controller: "EflWebBundle:Faqs:category"
                    template: "EflWebBundle:full:faqs_category.html.twig"
                    match:
                        Id\Location: 80
                faqs_category:
                    controller: "EflWebBundle:Faqs:category"
                    template: "EflWebBundle:full:faqs_category.html.twig"
                    match:
                        Id\ContentType: 65
                pagina_texto:
                    template: "EflWebBundle:full:pagina_texto.html.twig"
                    match:
                        Identifier\ContentType: pagina_texto

    global:
        field_templates:
            - {template: "EflWebBundle::content_fields.html.twig", priority: 10}

