siteaccess:
    groups:
        efl_frontend_group:
            - newhome
            - formacion
system:
    efl_frontend_group:
        image_variations:
            ebook_regalo:
                reference: reference
                filters:
                    - { name: geometry/scalewithdownonly, params: [480] }
        user:
            layout: EflWebBundle::pagelayout.html.twig
            login_template: eZDemoBundle:Security:login.html.twig
        content_view:
            ebook_regalo:
                ebook:
                    template: "EflWebBundle:ebook_regalo:ebook_regalo.html.twig"
                    match:
                        Identifier\ContentType: [ebook]
        location_view:
            full:
                producto:
                    template: "EflWebBundle:full:product.html.twig"
                    match:
                        Identifier\ContentType: [producto]
    global:
        field_templates:
            - {template: "EflWebBundle::content_fields.html.twig", priority: 10}

