parameters:
    efl.form.type.simple_search.class: Efl\WebBundle\Form\Type\SimpleSearchType
    efl.form.type.catalog_filters.class: Efl\WebBundle\Form\Type\Catalog\FiltersType

services:
    efl.form.type.simple_search:
        class: %efl.form.type.simple_search.class%
        tags:
            - { name: form.type, alias: efl_simple_search }

    efl.form.catalog_filters:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - efl_catalog_filters_form                        # name of the form
            - efl_catalog_filter                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    efl.form.type.catalog_filters:
        class: %efl.form.type.catalog_filters.class%
        arguments:
            - @eflweb.catalog_helper
            - @router
        tags:
            - { name: form.type, alias: efl_catalog_filter }

    validator.node.email_already_subscribed:
        class: Efl\WebBundle\Form\Validator\Constraints\EmailAlreadySubscribedValidator
        calls:
            - [setConnection, [@ezpublish.api.storage_engine.legacy.dbhandler]]
        tags:
            - { name: validator.constraint_validator, alias: email_already_subscribed }