parameters:
    eflweb.location_helper.class: Efl\WebBundle\Helper\LocationHelper
    eflweb.newsletter_helper.class: Efl\WebBundle\Helper\NewsletterHelper
    eflweb.nosotros_helper.class: Efl\WebBundle\Helper\NosotrosHelper
    eflweb.faqs_helper.class: Efl\WebBundle\Helper\FaqsHelper
    eflweb.buy_helper.class: Efl\WebBundle\Helper\BuyHelper
    eflweb.product_helper.class: Efl\WebBundle\Helper\ProductHelper
    eflweb.utils_helper.class: Efl\WebBundle\Helper\UtilsHelper
    eflweb.fechas_helper.class: Efl\WebBundle\Helper\FechasHelper
    eflweb.price_helper.class: Efl\WebBundle\Helper\PriceHelper
    eflweb.testimonies_helper.class: Efl\WebBundle\Helper\TestimoniesHelper
    eflweb.menus_helper.class: Efl\WebBundle\Helper\MenusHelper
    eflweb.leads_helper.class: Efl\WebBundle\Helper\LeadsHelper
    eflweb.qmemento_helper.class: Efl\WebBundle\Helper\QMementoHelper
    eflweb.catalog_helper.class: Efl\WebBundle\Helper\CatalogHelper
    eflweb.leads_client.parameters:

services:
    eflweb.location_helper:
        class: %eflweb.location_helper.class%
        arguments: [@ezpublish.api.repository]

    eflweb.newsletter_helper:
        class: %eflweb.newsletter_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content
            - @ezpublish.fieldtype.ezpage.pageservice
            - @ezpublish.controller.content.view
            - @ezpublish_legacy.kernel
            - @mailer
            - @templating
            - @router
            - @ezpublish_legacy.router
            - @eflweb.catalog_helper
            - %newsletter.subscription_mail%

    eflweb.nosotros_helper:
        class: %eflweb.nosotros_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search

    eflweb.testimonies_helper:
        class: %eflweb.testimonies_helper.class%
        arguments:
                - @ezpublish.api.service.location
                - @ezpublish.api.service.search
                - @ezpublish.api.service.content

    eflweb.faqs_helper:
        class: %eflweb.faqs_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content

    eflweb.buy_helper:
        class: %eflweb.buy_helper.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search

    eflweb.product_helper:
        class: %eflweb.product_helper.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.field_helper
            - @ezpublish.api.service.search
            - @eflweb.reviews_service
            - @ezpublish.api.service.content_type
            - @eflweb.controller.product.view
            - @eflweb.controller.product.reviews

    eflweb.utils_helper:
        class: %eflweb.utils_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @security.context

    eflweb.fechas_helper:
        class: %eflweb.fechas_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content
            - @ezpublish.translation_helper
        calls:
            - [setMonthsToShow]

    eflweb.price_helper:
        class: %eflweb.price_helper.class%
        arguments:
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.content
            - @eflweb.product_helper
            - @ezpublish.api.service.location
            - @eflweb.discounts_service
            - @ezpublish.api.repository

    eflweb.menus_helper:
        class: %eflweb.menus_helper.class%
        arguments:
            - @ezpublish.api.service.url_alias
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
        calls:
            - [setRequest, [@request_stack]]

    eflweb.leads_helper:
        class: %eflweb.leads_helper.class%
        arguments: ['%eflweb.leads_client.parameters%']

    eflweb.qmemento_helper:
        class: %eflweb.qmemento_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content

    eflweb.catalog_helper:
        class: %eflweb.catalog_helper.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
