parameters:
    eflweb.location_helper.class: Efl\WebBundle\Helper\LocationHelper
    eflweb.cart_helper.class: Efl\WebBundle\Helper\CartHelper
    eflweb.newsletter_helper.class: Efl\WebBundle\Helper\NewsletterHelper
    eflweb.nosotros_helper.class: Efl\WebBundle\Helper\NosotrosHelper
    eflweb.faqs_helper.class: Efl\WebBundle\Helper\FaqsHelper
    eflweb.buy_helper.class: Efl\WebBundle\Helper\BuyHelper

services:
    eflweb.location_helper:
        class: %eflweb.location_helper.class%
        arguments: [@ezpublish.api.repository]

    eflweb.cart_helper:
        class: %eflweb.cart_helper.class%
        arguments: [@ezpublish_legacy.kernel]

    eflweb.newsletter_helper:
        class: %eflweb.newsletter_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content
            - @ezpublish.fieldtype.ezpage.pageservice
            - @ezpublish.controller.content.view
            - @ezpublish_legacy.kernel
            - @mailer
            - @templating
            - @router
            - @ezpublish_legacy.router
            - %newsletter.subscription_mail%

    eflweb.nosotros_helper:
        class: %eflweb.nosotros_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search

    eflweb.faqs_helper:
        class: %eflweb.faqs_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.content

    eflweb.buy_helper:
        class: %eflweb.buy_helper.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
