# Newsletter
newsletter_subscribe:
    pattern:  /newsletter/subscribe
    defaults: { _controller: EflWebBundle:Newsletter:subscribe }

newsletter_configure:
    pattern: /newsletter/configure/{hash}
    defaults: { _controller: EflWebBundle:Newsletter:configure }

preview:
    pattern: "{url}/previusalizacion"
    defaults: { _controller: EflWebBundle:Product:preview }
    requirements:
        url: .+

summary:
    pattern: "{url}/sumario"
    defaults: { _controller: EflWebBundle:Product:summary }
    requirements:
        url: .+

video:
    pattern: /video/{locationId}
    defaults: { _controller: EflWebBundle:Product:video }

qmementix:
    pattern: /qmementix
    defaults: { _controller: EflWebBundle:QMementix:index }

qmementix_config:
    pattern: /qmementix/config
    defaults: { _controller: EflWebBundle:QMementix:config }

qmementix_postform:
    pattern: /qmementix/post
    defaults: { _controller: EflWebBundle:QMementix:postForm }
    methods: [POST]

imemento:
    pattern: /imemento
    defaults: { _controller: EflWebBundle:Imemento:index }

imemento_config:
    pattern: /imemento/config
    defaults: { _controller: EflWebBundle:Imemento:config }

imemento_postform:
    pattern: /imemento/post
    defaults: { _controller: EflWebBundle:Imemento:postForm }
    methods: [POST]

qmemento:
    pattern: /qmemento
    defaults: { _controller: EflWebBundle:QMemento:index }

qmemento_post:
    pattern: /qmemento/post
    defaults: { _controller: EflWebBundle:QMemento:postForm }
    methods: [POST]

