parameters:

    eflweb.social_links.linkedin: http://www.linkedin.com/company/ediciones-francis-lefebvre
    eflweb.social_links.twitter: https://twitter.com/edicionesfl
    eflweb.social_links.facebook: https://www.facebook.com/GrupoEFL
    eflweb.social_links.youtube: https://www.youtube.com/user/fmourelle

    eflweb.catalog.location_id: 61
    eflweb.catalog.mementos.location_id: 64
    eflweb.catalog.bases_datos.location_id: 13373
    eflweb.catalog.qmemento.location_id: 70
    eflweb.catalog.imemento.location_id: 11152
    eflweb.catalog.qmementix.location_id: 69
    eflweb.aviso_legal.location_id: 292
    eflweb.politica_privacidad.location_id: 19526
    eflweb.politica_cookies.location_id: 20410
    eflweb.twig.extension.metadata.class: Efl\WebBundle\Twig\Extensions\FezMetaDataExtension
    pagerfanta.view.efl.class: Efl\WebBundle\PagerFanta\View\EflView

services:
    eflweb.twig.extension.metadata:
            class: %eflweb.twig.extension.metadata.class%
            calls:
                - [setConnection, [@ezpublish.api.storage_engine.legacy.dbhandler]]
            tags:
                - {name: 'twig.extension'}

    eflweb.socialBarHelper:
        class : Efl\WebBundle\Templating\Helper\SocialBarHelper
        tags :
            - {name : 'templating.helper', alias : 'social-buttons'}
        arguments : [ @templating ]

    twig.extension.efl_social_bar:
        class: Efl\WebBundle\Twig\Extensions\EflTwigSocialBar
        tags:
            - { name: 'twig.extension' }
        arguments : [ @service_container ]

    pagerfanta.view.efl:
        class: %pagerfanta.view.efl.class%
        public: false
        tags:
            - { name: 'pagerfanta.view', alias: 'efl'}
