parameters:

    eflweb.social_links.linkedin: http://www.linkedin.com/company/ediciones-francis-lefebvre
    eflweb.social_links.twitter: https://twitter.com/edicionesfl
    eflweb.social_links.facebook: https://www.facebook.com/GrupoEFL
    eflweb.social_links.youtube: https://www.youtube.com/user/fmourelle

    eflweb.catalog.location_id: 61
    eflweb.catalog.mementos.location_id: 64
    eflweb.catalog.bases_datos.location_id: 13373
    eflweb.catalog.qmemento.location_id: 70
    eflweb.catalog.imemento.location_id: 11152
    eflweb.catalog.qmementix.location_id: 69
    eflweb.aviso_legal.location_id: 292
    eflweb.politica_privacidad.location_id: 19526
    eflweb.politica_cookies.location_id: 20410

    ezpublish.persistence.slug_converter.options:
        transformationGroups:
            urlalias:
                commands:
                    - "space_normalize"
                    - "hyphen_normalize"
                    - "apostrophe_normalize"
                    - "doublequote_normalize"
                    - "greek_normalize"
                    - "endline_search_normalize"
                    - "tab_search_normalize"
                    - "specialwords_search_normalize"
                    - "punctuation_normalize"
                    - "apostrophe_to_doublequote"
                    - "math_to_ascii"
                    - "inverted_to_normal"
                    - "special_decompose"
                    - "latin_search_decompose"
                    - "cyrillic_transliterate_ascii"
                    - "greek_transliterate_ascii"
                    - "hebrew_transliterate_ascii"
                    - "latin1_transliterate_ascii"
                    - "latin-exta_transliterate_ascii"
                    - "cyrillic_diacritical"
                    - "greek_diacritical"
                    - "latin1_diacritical"
                    - "latin-exta_diacritical"
                    - "ascii_lowercase"
                    - "cyrillic_lowercase"
                    - "greek_lowercase"
                    - "latin1_lowercase"
                    - "latin-exta_lowercase"
                    - "latin_lowercase"
                cleanupMethod: "url_cleanup"

services:
    # esto nos permitir치 mantener el comportamiento en creaci칩n de urls si decidimos usar api para crear contenidos.
    # de hecho es lo que hacemos en la creaci칩n de m칩dulos
    ezpublish.persistence.slug_converter:
        class: %ezpublish.persistence.slug_converter.class%
        arguments: [@ezpublish.api.storage_engine.transformation_processor, %ezpublish.persistence.slug_converter.options%]
