parameters:
    ezpublish.fieldType.customezpage.converter.class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page

services:
    ezpublish.fieldType.customezpage.converter:
        class: %ezpublish.fieldType.customezpage.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: customezpage}