parameters:
    ezpublish.fieldType.customezpage.converter.class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Page
    ezpublish.fieldType.dummy.converter.class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Null
    ezpublish.fieldType.ezobjectrelationbrowse.converter.class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\RelationList

services:
    ezpublish.fieldType.customezpage.converter:
        class: %ezpublish.fieldType.customezpage.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: customezpage}

    ezpublish.fieldType.ezobjectrelationbrowse.converter:
        class: %ezpublish.fieldType.ezobjectrelationbrowse.converter.class%
        arguments: [@ezpublish.api.storage_engine.legacy.dbhandler]
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezobjectrelationbrowse}

    ezpublish.fieldType.dummy.converter:
            class: %ezpublish.fieldType.dummy.converter.class%
            tags:
                - {name: ezpublish.storageEngine.legacy.converter, alias: dummy}