Efl\ReviewsBundle\Entity\ValoracionesProductos:
    type: entity
    table: valoraciones_productos
    indexes:
        node_producto:
            columns:
                - node_producto
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
        nodeProducto:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: node_producto
        haVotado:
            type: boolean
            nullable: true
            comment: ''
            column: ha_votado
        calidad:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        actualizaciones:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        facilidad:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        comentario:
            type: text
            nullable: true
            length: 65535
            fixed: false
            comment: ''
        visible:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        fecha:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        nombre:
            type: text
            nullable: false
            length: 65535
            fixed: false
            comment: ''
        apellidos:
            type: text
            nullable: false
            length: 65535
            fixed: false
            comment: ''
        empresa:
            type: text
            nullable: true
            length: 65535
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
