parameters:
    efl.discounts.product.legacy.class: Efl\DiscountsBundle\Discounts\Product\Legacy
    efl.discounts.product.coupon.class: Efl\DiscountsBundle\Discounts\Product\Coupon

services:
    efl.discounts.product.legacy:
        class: %efl.discounts.product.legacy.class%
        arguments:
            - @eflweb.discounts_service
            - @ezpublish.api.repository
        tags:
          -  { name: efl.discounts.product, alias: legacy }

    efl.discounts.product.coupon:
        class: %efl.discounts.product.coupon.class%
        arguments:
            - @eflweb.basket_service
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.api.service.search
            - @ezpublish.api.repository
        tags:
          -  { name: efl.discounts.product, alias: legacy }