product_reviews:
    pattern: /reviews/{locationId}/page/{page}
    defaults: { _controller: EflReviewsBundle:Reviews:pager, page:1 }
    requirements:
      page: \d+
      locationId: \d+

create_review:
    pattern: /review/create/{locationId}
    defaults: { _controller: EflReviewsBundle:Reviews:createReview }
    requirements:
      page: \d+
      locationId: \d+