parameters:
    # API services
    eflweb.repository.reviews_service.class: Efl\ReviewsBundle\eZ\Publish\Core\Repository\ReviewsService
    eflweb.persistence.legacy.reviews.handler.class: Efl\ReviewsBundle\eZ\Publish\Core\Persistence\Legacy\Reviews\Handler
    eflweb.persistence.legacy.reviews.gateway.class: Efl\ReviewsBundle\eZ\Publish\Core\Persistence\Legacy\Reviews\Gateway\Doctrine
    eflweb.reviews_per_page: 5
    eflweb.controller.product.reviews.class: Efl\ReviewsBundle\Controller\ReviewsController

services:
    eflweb.reviews_service:
        class: %eflweb.repository.reviews_service.class%
        arguments:
            - @ezpublish.api.repository
            - @eflweb.persistence.legacy.reviews.handler

    eflweb.persistence.legacy.reviews.handler:
        class: %eflweb.persistence.legacy.reviews.handler.class%
        arguments:
            - @eflweb.persistence.legacy.reviews.gateway.inner

    eflweb.persistence.legacy.reviews.gateway.inner:
        class: %eflweb.persistence.legacy.reviews.gateway.class%
        arguments:
            - @doctrine.orm.entity_manager

    eflweb.controller.product.reviews:
        class: %eflweb.controller.product.reviews.class%
        parent: ezpublish.controller.base