parameters:
    efl.basket.shipping.efl.class: Efl\ShippingBundle\ShippingMethod\Efl

services:
    efl.basket.shiping.efl:
        class: %efl.basket.shipping.efl.class%
        tags:
            -  { name: efl.shipping, alias: efl }
