parameters:
    eflweb.listener.messages.class: Efl\MessagesBundle\Listeners\Messages

services:
    eflweb.listener.messages.basket.item.add:
        class: %eflweb.listener.messages.class%
        arguments:
            - @session
            - @translator
        tags:
            - { name: kernel.event_listener, event: eflweb.event.basket.additem, method: onAddItemToBasket }

    eflweb.listener.messages.basket.item.remove:
            class: %eflweb.listener.messages.class%
            arguments:
                - @session
                - @translator
            tags:
                - { name: kernel.event_listener, event: eflweb.event.basket.removeitem, method: onRemoveItemFromBasket }

    eflweb.listener.messages.basket.item.update:
            class: %eflweb.listener.messages.class%
            arguments:
                - @session
                - @translator
            tags:
                - { name: kernel.event_listener, event: eflweb.event.basket.updateitem, method: onUpdateItemInBasket }
